CREATE TABLE `fee_group` (
`FEE_GROUP_ID` int(11) NOT NULL AUTO_INCREMENT,
`NAME` varchar(128) DEFAULT NULL,
`EFFECTIVE_START_DATE` date DEFAULT NULL,
`EFFECTIVE_END_DATE` date DEFAULT NULL,
`ACTIVE_IND` tinyint(1) DEFAULT '1',
PRIMARY KEY (`FEE_GROUP_ID`),
UNIQUE KEY `UNIQUE_fee_grp` (`NAME`)
);

CREATE TABLE `ref_fee_type` (
`FEE_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
`FEE_TYPE` varchar(45) NOT NULL,
`DESCRIPTION` varchar(45) DEFAULT NULL,
PRIMARY KEY (`FEE_TYPE_ID`)
);

CREATE TABLE `fee` (
`FEE_ID` int(15) NOT NULL AUTO_INCREMENT,
`FEE_GROUP_ID` int(15) DEFAULT NULL,
`FEE_TYPE_ID` int(11) DEFAULT NULL,
`TYPE` varchar(45) DEFAULT NULL,
`FEE_NAME` varchar(45) DEFAULT NULL,
`FEE` double(21,4) DEFAULT NULL,
`EFFECTIVE_START_DATE` date DEFAULT NULL,
`EFFECTIVE_END_DATE` date DEFAULT NULL,
`ACTIVE_IND` tinyint(1) DEFAULT '1',
`IS_DEBIT` tinyint(1) DEFAULT '0',
PRIMARY KEY (`FEE_ID`),
KEY `FK_FEE_GROUP_idx` (`FEE_GROUP_ID`),
KEY `FK_FEE_002` (`FEE_TYPE_ID`),
CONSTRAINT `FK_FEE_001` FOREIGN KEY (`FEE_GROUP_ID`) REFERENCES `fee_group` (`FEE_GROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_FEE_002` FOREIGN KEY (`FEE_TYPE_ID`) REFERENCES `ref_fee_type` (`FEE_TYPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE `ref_service_broker` (
`SERVICE_BROKER_ID` int(11) NOT NULL AUTO_INCREMENT,
`SERVICE_BROKER_NAME` varchar(20) DEFAULT NULL,
`SERVICE_BROKER_DESC` varchar(45) DEFAULT NULL,
`ACTIVE` tinyint(1) DEFAULT NULL,
PRIMARY KEY (`SERVICE_BROKER_ID`)
);

CREATE TABLE `ref_service_provider` (
`SERVICE_PROVIDER_ID` int(11) NOT NULL AUTO_INCREMENT,
`SERVICE_BROKER_ID` int(11) NOT NULL,
`SERVICE_PROVIDER_SHORT_NAME` varchar(20) DEFAULT NULL,
`SERVICE_PROVIDER_DISPLAY_NAME` varchar(80) DEFAULT NULL,
`SERVICE_PROVIDER_TYPE` varchar(45) DEFAULT NULL,
`CITY` varchar(45) DEFAULT NULL,
`SORT_ORDER` int(11) DEFAULT NULL,
`ACTIVE` tinyint(1) DEFAULT NULL,
PRIMARY KEY (`SERVICE_PROVIDER_ID`),
KEY `FK_REF_SERVICE_PROVIDER_001_idx` (`SERVICE_BROKER_ID`),
CONSTRAINT `FK_REF_SERVICE_PROVIDER_001` FOREIGN KEY (`SERVICE_BROKER_ID`) REFERENCES `ref_service_broker` (`SERVICE_BROKER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

create table ref_service_type
(
    id int auto_increment not null,
    value varchar(255) null,
    description varchar(255) null,
    constraint ref_service_type_pk
        primary key (id)
);

CREATE TABLE `ref_service` (
`SERVICE_ID` int(11) NOT NULL,
`SERVICE_NAME` varchar(255) DEFAULT NULL,
`PRICE` double(21,2) DEFAULT NULL,
`RETAIL_PRICE` double(21,2) DEFAULT NULL,
`SERVICE_TYPE_ID` int(11) DEFAULT NULL,
`SERVICE_PROVIDER_ID` int(11) DEFAULT NULL,
`SORT_ORDER` int(11) DEFAULT NULL,
`ACTIVE` tinyint(1) DEFAULT NULL,
`SERVICE_CODE` varchar(100) DEFAULT NULL,
PRIMARY KEY (`SERVICE_ID`),
KEY `FK_REF_SERVICE_001_idx` (`SERVICE_TYPE_ID`),
KEY `FK_REF_SERVICE_002_idx` (`SERVICE_PROVIDER_ID`),
CONSTRAINT `FK_REF_SERVICE_001` FOREIGN KEY (`SERVICE_TYPE_ID`) REFERENCES `ref_service_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_REF_SERVICE_002` FOREIGN KEY (`SERVICE_PROVIDER_ID`) REFERENCES `ref_service_provider` (`SERVICE_PROVIDER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE `service_fee_group` (
`SERVICE_FEE_GROUP_ID` int(15) NOT NULL AUTO_INCREMENT,
`FEE_GROUP_ID` int(15) DEFAULT NULL,
`SERVICE_ID` int(15) DEFAULT NULL,
`EFFECTIVE_START_DATE` date DEFAULT NULL,
`EFFECTIVE_END_DATE` date DEFAULT NULL,
`ACTIVE_IND` tinyint(1) DEFAULT '1',
PRIMARY KEY (`SERVICE_FEE_GROUP_ID`),
KEY `FK_SERVICE_FEE_GROUP_001_idx` (`SERVICE_ID`),
KEY `FK_SERVICE_FEE_GROUP_002_idx` (`FEE_GROUP_ID`),
CONSTRAINT `FK_SERVICE_FEE_GROUP_002` FOREIGN KEY (`FEE_GROUP_ID`) REFERENCES `fee_group` (`FEE_GROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_SERVICE_FEE_GROUP_003` FOREIGN KEY (`SERVICE_ID`) REFERENCES `ref_service` (`SERVICE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE `user_group` (
`USER_GROUP_ID` int(11) NOT NULL AUTO_INCREMENT,
`NAME` varchar(64) NOT NULL,
`TYPE` varchar(64) DEFAULT NULL,
`EFFECTIVE_START_DATE` date DEFAULT NULL,
`EFFECTIVE_END_DATE` date DEFAULT NULL,
`ACTIVE_IND` tinyint(1) DEFAULT '1',
PRIMARY KEY (`USER_GROUP_ID`),
UNIQUE KEY `usr_grp_name_unq` (`NAME`)
);

CREATE TABLE `user_group_service_fee_group` (
`USER_GROUP_SERVICE_FEE_GROUP_ID` int(11) NOT NULL AUTO_INCREMENT,
`SERVICE_FEE_GROUP_ID` int(15) DEFAULT NULL,
`USER_GROUP_ID` int(15) DEFAULT NULL,
`EFFECTIVE_START_DATE` date NOT NULL DEFAULT '2014-01-01',
`EFFECTIVE_END_DATE` date NOT NULL DEFAULT '2040-01-01',
`ACTIVE_IND` tinyint(1) DEFAULT '1',
PRIMARY KEY (`USER_GROUP_SERVICE_FEE_GROUP_ID`),
UNIQUE KEY `Ser_Grp_Unq` (`SERVICE_FEE_GROUP_ID`,`USER_GROUP_ID`),
KEY `FK_USER_GROUP_FEE_GROUP_001_idx` (`USER_GROUP_ID`),
KEY `FK_USER_GROUP_FEE_GROUP_002_idx` (`SERVICE_FEE_GROUP_ID`),
CONSTRAINT `FK_USER_GROUP_FEE_GROUP_001` FOREIGN KEY (`USER_GROUP_ID`) REFERENCES `user_group` (`USER_GROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `FK_USER_GROUP_FEE_GROUP_002` FOREIGN KEY (`SERVICE_FEE_GROUP_ID`) REFERENCES `service_fee_group` (`SERVICE_FEE_GROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE `ref_service_provider_type` (
`SERVICE_PROVIDER_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
`SERVICE_PROVIDER_TYPE` varchar(45) NOT NULL,
`DESCRIPTION` varchar(45) DEFAULT NULL,
PRIMARY KEY (`SERVICE_PROVIDER_TYPE_ID`)
);