INSERT INTO `zingpay`.`ref_service_broker` (`SERVICE_BROKER_ID`, `SERVICE_BROKER_NAME`, `SERVICE_BROKER_DESC`, `ACTIVE`) VALUES ('1', 'NADRA', 'NADRA', '1');


INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('10', '1', 'fwasa', 'Faisalabad Water And Sanitation Agency', 'WATER_SUPPLY_SANITATION', 'Faisalabad', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('11', '1', 'gepco', 'Gujranwala Electric Power Company', 'ELECTRIC', 'Gujranwala', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('12', '1', 'hesco', 'Hyderabad Electric Supply Company','ELECTRIC','Hyderabad', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('13', '1', 'kesc', 'Karachi Electric Supply Company','ELECTRIC','Karachi', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('14', '1', 'kwsb', 'Karachi Water Supply Board','WATER_SUPPLY_SANITATION','Karachi', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('15', '1', 'sepco', 'Sukkur Electric Power Company','ELECTRIC','Sukkur', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('16', '1', 'sngpl', 'Sui Northern Gas Pipelines Limited','GAS','ALL', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('17', '1', 'ssgc', 'Sui Southern Gas Company','GAS','ALL', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('18', '1', 'lesco', 'Lahore Electric Supply Company','ELECTRIC','Lahore', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('19', '1', 'mepco', 'Multan Electric Power Company','ELECTRIC','Multan', '1', '1');
INSERT INTO `zingpay`.`ref_service_provider` (`SERVICE_PROVIDER_ID`, `SERVICE_BROKER_ID`, `SERVICE_PROVIDER_SHORT_NAME`, `SERVICE_PROVIDER_DISPLAY_NAME`, `SERVICE_PROVIDER_TYPE`, `CITY`, `SORT_ORDER`, `ACTIVE`) VALUES ('20', '1', 'pesco', 'Peshawar Electric Supply Company','ELECTRIC', 'Peshawar', '1', '1');


INSERT INTO `zingpay`.`ref_service_type` (`id`, `value`, `description`) VALUES ('3', 'BILLPAYMENT', 'BILLPAYMENT');


INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 100, 'ZINGPAY_BILLPAY(FWASA)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'fwasa' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 101, 'ZINGPAY_BILLPAY(GEPCO)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'gepco' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 102, 'ZINGPAY_BILLPAY(HESCO)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'hesco' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 103, 'ZINGPAY_BILLPAY(KESC)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'kesc' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 104, 'ZINGPAY_BILLPAY(KWSB)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'kwsb' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 105, 'ZINGPAY_BILLPAY(SEPCO)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'sepco' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 106, 'ZINGPAY_BILLPAY(SNGPL)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'sngpl' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 107, 'ZINGPAY_BILLPAY(SSGC)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'ssgc' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 108, 'ZINGPAY_BILLPAY(LESCO)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'lesco' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 109, 'ZINGPAY_BILLPAY(MEPCO)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'mepco' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');
INSERT INTO ref_service (SERVICE_ID, SERVICE_NAME, SERVICE_TYPE_ID,SERVICE_PROVIDER_ID,ACTIVE) Select 110, 'ZINGPAY_BILLPAY(PESCO)',(Select id from ref_service_type rst where rst.value = 'BILLPAYMENT'), SERVICE_PROVIDER_ID, 1 from ref_service_provider where SERVICE_PROVIDER_SHORT_NAME = 'pesco' and SERVICE_BROKER_ID =(select SERVICE_BROKER_ID from ref_service_broker where SERVICE_BROKER_NAME = 'NADRA');


INSERT INTO `zingpay`.`fee_group` (`NAME`, `ACTIVE_IND`) VALUES ('BILLPAYMENT_NADRA_DEFAULT', '1'), ('BILLPAYMENT_NADRA_ZINGPAY', '1'), ('BILLPAYMENT_NADRA_AGENT_MASTER', '1'), ('BILLPAYMENT_NADRA_AGENT', '1');


insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 100, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 101, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 102, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 103, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 104, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 105, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 106, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 107, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 108, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 109, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 110, fee_group_id, 1 from fee_group where name like '%BILLPAYMENT_NADRA%';


insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 100 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 100 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 100 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 100 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 101 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 101 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 101 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 101 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 102 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 102 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 102 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 102 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 103 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 103 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 103 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 103 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 104 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 104 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 104 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 104 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 105 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 105 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 105 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 105 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 106 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 106 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 106 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 106 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 107 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 107 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 107 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 107 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 108 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 108 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 108 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 108 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 109 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 109 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 109 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 109 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 1, service_fee_group_id, 1 from service_fee_group where service_id = 110 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 2, service_fee_group_id, 1 from service_fee_group where service_id = 110 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 3, service_fee_group_id, 1 from service_fee_group where service_id = 110 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select 4, service_fee_group_id, 1 from service_fee_group where service_id = 110 and fee_group_id in (select fee_group_id from fee_group where name like '%BILLPAYMENT_NADRA_AGENT');

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_COMMISSION', 'COMMISSION', 7, 1 from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like '%BILLPAYMENT_NADRA_DEFAULT';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_COMMISSION', 'COMMISSION', 100, 1 from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like '%BILLPAYMENT_NADRA_ZINGPAY';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like '%BILLPAYMENT_NADRA_AGENT_MASTER';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like '%BILLPAYMENT_NADRA_AGENT';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 1, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like '%BILLPAYMENT_NADRA_AGENT';