INSERT INTO fee_group (NAME, ACTIVE_IND) VALUES
('LOAD_TELENOR_IMEDIA', '1'), ('LOAD_TELENOR_IMEDIA_HANDLERS', '1'), ('LOAD_TELENOR_IMEDIA_CABLE_OPERATOR', '1'), ('LOAD_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS', '1'), ('LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR', '1'), ('LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS', '1'),
('BUNDLE_TELENOR_IMEDIA', '1'), ('BUNDLE_TELENOR_IMEDIA_HANDLERS', '1'), ('BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR', '1'), ('BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS', '1'), ('BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR', '1'), ('BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS', '1');

insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 150, fee_group_id, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 151, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 152, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 153, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 154, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 155, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 156, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 157, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 158, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 159, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 160, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 161, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 162, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 163, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 164, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 165, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 166, fee_group_id, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA%';

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 150 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 150 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 150 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 150 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 150 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 150 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 151 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 151 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 151 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 151 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 151 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 151 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 152 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 152 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 152 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 152 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 152 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 152 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 153 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 153 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 153 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 153 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 153 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 153 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 154 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 154 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 154 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 154 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 154 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 154 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 155 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 155 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 155 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 155 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 155 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 155 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 156 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 156 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 156 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 156 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 156 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 156 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 157 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 157 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 157 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 157 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 157 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 157 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 158 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 158 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 158 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 158 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 158 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 158 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 159 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 159 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 159 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 159 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 159 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 159 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 160 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 160 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 160 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 160 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 160 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 160 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 161 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 161 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 161 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 161 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 161 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 161 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 162 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 162 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 162 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 162 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 162 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 162 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 163 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 163 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 163 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 163 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 163 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 163 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 164 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 164 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 164 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 164 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 164 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 164 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 165 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 165 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 165 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 165 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 165 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 165 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 166 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 166 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 166 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 166 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 166 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 166 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');


insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 4, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 100, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_OPERATOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_OPERATOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';


insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 4, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 100, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_OPERATOR_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_TELENOR_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';