INSERT INTO fee_group (NAME, ACTIVE_IND) VALUES
('BUNDLE_CARDWALLA_IMEDIA', '1'), ('BUNDLE_CARDWALLA_IMEDIA_HANDLERS', '1'), ('BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR', '1'), ('BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS', '1'), ('BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR', '1'), ('BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS', '1');

insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 200, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 201, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 202, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 203, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 204, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 205, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 206, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 207, fee_group_id, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA%';


insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 200 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 200 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 200 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 200 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 200 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 200 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 201 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 201 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 201 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 201 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 201 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 201 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 202 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 202 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 202 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 202 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 202 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 202 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 203 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 203 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 203 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 203 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 203 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 203 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 204 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 204 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 204 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 204 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 204 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 204 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 205 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 205 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 205 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 205 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 205 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 205 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 206 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 206 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 206 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 206 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 206 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 206 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 207 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 207 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 207 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 207 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 207 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 207 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_OPERATOR_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_CARDWALLA_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';