INSERT INTO fee_group (NAME, ACTIVE_IND) VALUES
('LOAD_ZONG_IMEDIA', '1'), ('LOAD_ZONG_IMEDIA_HANDLERS', '1'), ('LOAD_ZONG_IMEDIA_CABLE_OPERATOR', '1'), ('LOAD_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS', '1'), ('LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR', '1'), ('LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS', '1'),
('BUNDLE_ZONG_IMEDIA', '1'), ('BUNDLE_ZONG_IMEDIA_HANDLERS', '1'), ('BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR', '1'), ('BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS', '1'), ('BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR', '1'), ('BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS', '1');

insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 50, fee_group_id, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 51, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 52, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 53, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 54, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 55, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 56, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 57, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 58, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 59, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 60, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 61, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 62, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 63, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 64, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 65, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 66, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 67, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 68, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 69, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 70, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 71, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 72, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 73, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 74, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 75, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';
insert into service_fee_group (service_id, fee_group_id, ACTIVE_IND) select 76, fee_group_id, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA%';


insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 50 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 50 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 50 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 50 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 50 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 50 and fee_group_id in (select fee_group_id from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 51 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 51 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 51 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 51 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 51 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 51 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 52 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 52 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 52 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 52 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 52 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 52 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 53 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 53 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 53 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 53 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 53 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 53 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 54 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 54 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 54 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 54 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 54 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 54 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 55 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 55 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 55 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 55 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 55 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 55 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 56 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 56 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 56 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 56 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 56 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 56 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 57 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 57 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 57 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 57 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 57 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 57 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 58 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 58 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 58 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 58 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 58 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 58 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 59 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 59 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 59 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 59 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 59 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 59 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 60 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 60 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 60 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 60 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 60 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 60 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 61 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 61 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 61 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 61 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 61 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 61 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 62 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 62 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 62 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 62 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 62 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 62 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 63 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 63 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 63 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 63 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 63 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 63 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 64 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 64 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 64 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 64 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 64 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 64 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 65 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 65 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 65 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 65 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 65 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 65 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 66 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 66 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 66 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 66 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 66 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 66 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 67 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 67 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 67 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 67 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 67 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 67 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 68 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 68 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 68 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 68 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 68 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 68 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 69 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 69 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 69 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 69 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 69 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 69 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 70 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 70 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 70 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 70 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 70 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 70 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 71 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 71 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 71 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 71 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 71 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 71 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 72 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 72 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 72 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 72 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 72 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 72 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 73 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 73 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 73 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 73 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 73 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 73 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 74 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 74 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 74 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 74 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 74 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 74 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 75 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 75 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 75 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 75 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 75 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 75 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');

insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA'), service_fee_group_id, 1 from service_fee_group where service_id = 76 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 76 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR'), service_fee_group_id, 1 from service_fee_group where service_id = 76 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_OPERATOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 76 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR'), service_fee_group_id, 1 from service_fee_group where service_id = 76 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR');
insert into user_group_service_fee_group (user_group_id, service_fee_group_id, ACTIVE_IND) select (SELECT USER_GROUP_ID from user_group where NAME = 'IMEDIA_CABLE_DISTRIBUTOR_HANDLERS'), service_fee_group_id, 1 from service_fee_group where service_id = 76 and fee_group_id in (select fee_group_id from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS');


insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_HANDLERS';


insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_OPERATOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_OPERATOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'LOAD_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';


insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_OPERATOR_HANDLERS';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 70, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR';

insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_COMMISSION', 'COMMISSION', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';
insert into fee (fee_group_id, fee_type_id, type, fee_name, fee, active_ind) select fee_group_id, 2, 'TX_SERVICE_CHARGE', 'SERVICE CHARGE', 0, 1 from fee_group where name like 'BUNDLE_ZONG_IMEDIA_CABLE_DISTRIBUTOR_HANDLERS';