INSERT INTO app_user (PARENT_ID,BRANCH_ID,GROUP_ID,ACCOUNT_STATUS_ID,ACCOUNT_TYPE_ID,USERNAME,PASSWORD,FULL_NAME,ADDRESS,CELL_PHONE,EMAIL,CNIC_NUMBER,ALTERNATE_CELL_PHONE,LAST_LOGIN,CREATED_DATE_TIME,CREATED_BY,MODIFIED_DATE_TIME,MODIFIED_BY,SUSPEND_DATE_TIME,T_PIN,LOGIN_FAILED_COUNT,IS_GENERATED_T_PIN, device_id,service_type_id,cnic_issue_date,deposit_type_id,house_type_id,kyc_status_id,transaction_amount,transaction_date)
VALUES
(0,1,(SELECT USER_GROUP_ID from user_group where NAME='DEFAULT'),1,3,'SYSTEM',NULL,'SYSTEM',NULL,'00000000000',NULL,NULL,'00000000000',0,0,0,0,0,0,NULL,0,1,0,0,0,0,0,0,0,0);
INSERT INTO app_user
(PARENT_ID,BRANCH_ID,GROUP_ID,ACCOUNT_STATUS_ID,ACCOUNT_TYPE_ID,USERNAME,PASSWORD,FULL_NAME,ADDRESS,CELL_PHONE,EMAIL,CNIC_NUMBER,ALTERNATE_CELL_PHONE,LAST_LOGIN,CREATED_DATE_TIME,CREATED_BY,MODIFIED_DATE_TIME,MODIFIED_BY,SUSPEND_DATE_TIME,T_PIN,LOGIN_FAILED_COUNT,IS_GENERATED_T_PIN, device_id,service_type_id,cnic_issue_date,deposit_type_id,house_type_id,kyc_status_id,transaction_amount,transaction_date)
VALUES
(0,1,(SELECT USER_GROUP_ID from user_group where NAME='ZINGPAY'),1,3,'ZINGPAY',NULL,'ZINGPAY',NULL,'11111111111',NULL,NULL,'00000000000',0,0,0,0,0,0,NULL,0,1,0,0,0,0,0,0,0,0);

INSERT INTO app_user
(PARENT_ID,BRANCH_ID,GROUP_ID,ACCOUNT_STATUS_ID,ACCOUNT_TYPE_ID,USERNAME,PASSWORD,FULL_NAME,ADDRESS,CELL_PHONE,EMAIL,CNIC_NUMBER,ALTERNATE_CELL_PHONE,LAST_LOGIN,CREATED_DATE_TIME,CREATED_BY,MODIFIED_DATE_TIME,MODIFIED_BY,SUSPEND_DATE_TIME,T_PIN,LOGIN_FAILED_COUNT,IS_GENERATED_T_PIN, device_id,service_type_id,cnic_issue_date,deposit_type_id,house_type_id,kyc_status_id,transaction_amount,transaction_date)
VALUES
(0,1,0,1,3,'GJHERJKGH','{bcrypt}$2a$10$VlhfyywhdHwEBZTJD5Wk5u8qFImoN/ZhDQPFlC15KPIXivGR3hz36','TELENOR BANK',NULL,'22222222222',NULL,NULL,'00000000000',0,0,0,0,0,0,NULL,0,1,0,0,0,0,0,0,0,0);
